#lang racket
(require "../ao/dsl.rkt")
(provide name render)
(define name "Rings")
(define (render a)
  (define pulse (+ .14 (* .13 (audio-frame-loudness a))))
  (scene (rgb .012 .008 .03)
         (list
          (gradient-circle .5 .5 (* 2.4 pulse) (rgba* .22 .03 .8 .12) (rgba* .02 .0 .12 0))
          (group
           (for/list ([i (in-range 28)])
             (define angle (* i (/ (* 2 pi) 28)))
             (define level (list-ref (audio-frame-spectrum a) (modulo (* i 2) 48)))
             (gradient-circle (+ .5 (* (+ .14 (* .22 level)) (cos angle)))
                              (+ .5 (* (+ .14 (* .22 level)) (sin angle)))
                              (+ .006 (* .027 level))
                              (rgba* .5 (+ .25 (* .65 level)) 1.0 .95)
                              (rgba* .08 .02 .4 0)))
           0 0 1 (* .11 (audio-frame-time a)) 1 "add")
          (gradient-circle .5 .5 pulse (rgba* .75 .13 1.0 .7) (rgba* .2 .01 .55 0)))))
